---
title: "EDA"
author: "Danny Luo"
date: "4/18/2021"
output: pdf_document
---
```{r}
library(dplyr)
library(factoextra)
```

```{r}
data <- read.delim("../data-final.csv",header=TRUE,skipNul= TRUE,na.strings = "NULL")

```

```{r}
head(data)
```

```{r}
#take only response data
data_reduced <- data[,1:50]

#change to numeric
for(i in 1:50){
  data_reduced[,i]=as.numeric(data_reduced[,i])-1
}

pos_keyed_vars <-  c('EXT1', 'EXT3', 'EXT5', 'EXT7', 'EXT9',
                    'EST1', 'EST3', 'ESdatT5', 'EST6', 'EST7', 
                    'EST8', 'EST9', 'EST10',
                    'AGR2', 'AGR4', 'AGR6', 'AGR8', 'AGR9', 'AGR10',
                    'CSN1', 'CSN3', 'CSN5', 'CSN7', 'CSN9', 'CSN10', 
                    'OPN1', 'OPN3', 'OPN5', 'OPN7', 'OPN8', 'OPN9', 
                    'OPN10')
neg_keyed_vars <-  c('EXT2', 'EXT4', 'EXT6', 'EXT8', 'EXT10',
                    'EST2', 'EST4',
                    'AGR1', 'AGR3', 'AGR5', 'AGR7', 
                    'CSN2', 'CSN4', 'CSN6', 'CSN8', 
                    'OPN2', 'OPN4', 'OPN6')

for(key in neg_keyed_vars){
  data_reduced[key]=6-data_reduced[key]
}

rowSums(data_reduced[1:10])
score_data <- data_reduced %>% mutate(
                                    EST=rowSums(data_reduced[11:20])/10,
                                    EXT=rowSums(data_reduced[1:10])/10,
                                    OPN=rowSums(data_reduced[41:50])/10,
                                    AGR=rowSums(data_reduced[21:30])/10,
                                    CSN=rowSums(data_reduced[31:40])/10)
score_data1 <- score_data[,51:55]
score_data_final<-na.omit(score_data1)
```
```{r}
fviz_nbclust(score_data_final,FUNcluster = kmeans, method = "silhouette")
```


```{r}
M<-kmeans(score_data_final, 4)
centers <- kmeans(score_data_final, 4)$centers

par(mfrow=c(2,2),mar=c(3,3,1,1),mgp=c(1.75,.75,0))
plot(x=1:5,centers[1,],ylim = c(0,5))
plot(x=1:5,centers[2,],ylim = c(0,5))
plot(x=1:5,centers[3,],ylim = c(0,5))
plot(x=1:5,centers[4,],ylim = c(0,5))


```

```{r}
score_data <- cbind(score_data_final, cluster = M$cluster)
head(score_data)
```

```{r}
group<-split(score_data, score_data$cluster)
group[1]
group[2]
```




```{r}
kmeans(score_data_final, 10)

```


```{r}
library(mixAK)
VARS <- names(score_data_final)[1:5]
Prior <- list(priorK = "fixed", Kmax = 4,lambda=5)
nMCMC <- c(burn=5000, keep=10000, thin=5, info=1000)
fit_personality <- NMixMCMC(y0=score_data_final[1:1000,],prior=Prior,nMCMC=nMCMC,scale=list(shift=0, scale=1))



fit_personality[[1]]$poster.mean.w
fit_personality[[1]]$poster.mean.mu[,1]
fit_personality[[1]]$mixture
### clustering
NMixPlugDA(fit_personality[[1]], score_data_final[1:1000,])
par(mfrow=c(2,2))
for(i in 1:4){
  plot(x=1:4,y=fit_personality[[1]]$poster.mean.mu[,i],ylim=c(0,5))
}
```




