---
title: "Bayesian Unsupervised Clustering Method For Uncovering Latent Personality Types "
author: "Boxuan Li, Nianli Peng, Danny Luo"
date: "4/24/2021"
output:
  bookdown::pdf_document2
bibliography: mybib.bib
link-citations: yes
csl: ieee.csl
nocite: '@*'
---
# Introduction

The Five Factor Model (FFM) of personality is a model for personality assessment that has been widely studied and applied in the field of Psychology. [@FFM_intro] It proposes 5 domains across which one's personality could be characterized. They are Openness to Experience, Conscientiousness, Extraversion, Agreeableness and Neuroticism (or in abbreviation, OCEAN) respectively. 

While FFM presents a viable framework to evaluate individual personality's scores on those five traits, it does not identify any personality type by itself. To fully extract the value from FFM data usually means analyzing in depths the interaction between each dimensions or moving a step further in classifying individuals into homogenous personality profiles that could be interpretable under FFM.[@merz_latent_2011] Identifying those latent personality types will be of trememdous psychometric values. It will not only reveal correlations between each dimension of personality traits, but will also present us a fuller picture of compositions of human personalities. An ideal latent personality classification would also yield a simple and univariate measure of individual personality, that could be used in causal inference and prediction widely in the field of psychology and behavioral science. 

Recent literatures have attempted with various techniques to approach this clustering tasks to identify personality types from FFM, including Latent Profile Analysis, Gaussian Mixture Model combined with Factor Analysis. [@merz_latent_2011,@gerlach_robust_2018] 

We propose an Bayesian unsupervised clustering algorithm that leverages a two-fold modeling structure:

- A non-parametric Dirichlet process Gaussian mixture model to estimate size of clusters and their respective subpopulation parameters using a small portion of data
- Feed the above result as prior into Gaussian mixture model with fixed cluster size, utilizing the rest of our data

We adopt this two phase modeling due to expensive computational cost given the gigantic dataset. The final output will yield a clustering of all individuals into different latent personalities type that is highly interpretable using FFM framework. 

# Data

A couple of paragraphs describing the data to be used. You may wish to
discuss: (i) data sources – where are you getting the data? (ii) data description –
what data / variables will be used for modeling? (iii) data type – ordinal discrete,
nominal discrete, continuous, etc., and (iv) data scraping / wrangling – how to
extract and clean data for modeling? See project rubric for details

```{r gg-oz-plot, echo=FALSE,  message=FALSE,warning=FALSE,fig.cap = "Life expectancy from 1952 - 2007 for Australia. Life expentancy increases steadily except from 1962 to 1969. We can safely say that our life expectancy is higher than it has ever been!"}
library(ggplot2)
library(dplyr)
library(gapminder)
gapminder %>%
  filter(country == "Australia") %>%
  ggplot(aes(x = year,
             y = lifeExp)) + 
  geom_point()
```




# Model
$$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$$
\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation} 

: Discussion & justification of the proposed Bayesian model framework
(prior and sampling model). This discussion should elicit prior information on the
problem, the data sources available, and relevant project goals. Any “downstream”
uses of the model (e.g., for prediction, optimization, ranking) should be discussed
in detail here. See project rubric for details.


This is test for referencing equation. See equation \@ref(eq:binom)

# Results
Posterior analyses from the fitted Bayesian model, and a translation of
such findings into meaningful & understandable conclusions for the target audience
(e.g., engineers, business managers, policy-makers, etc). See project rubric for
details.


# Conclusion





A summary of key findings and potential impacts of your project.



# References {-}

<div id="refs"></div>

# Appendix {-}

