---
title: "Model_run"
author: "Danny Luo"
date: "4/29/2021"
output: html_document
---

```{r}

# Result from DP
my_data <- readRDS("DP_result_updated.rds")
my_data$clusterParameters$mu[,,2]
par(mfrow=c(4,4))

# selection threshold
epsilon=0.10
S=10000

# retain cluster if only size >= epsilon * S
cluster_final_indx <- c()
for(i in 1:my_data$numberClusters){
  if(my_data$pointsPerCluster[i]>=epsilon*S){
    cluster_final_indx <- c(cluster_final_indx,i)
  }
}

# Plot cluster means 
par(mfrow=c(2,4))
for(i in cluster_final_indx){
  plot(x=1:5,y=my_data$clusterParameters$mu[,,i],ylim=c(-3,3),
       xlab = "subtraits",ylab="score", 
       main=paste(" mean for cluster",i),
       sub=paste(round(my_data$pointsPerCluster[i]/S*100,2),"%total population"),
       xaxt="n")
  axis(side = 1, at = 1:5,labels = c("E","N","A","C","O"))
}

#'Extroversion', 'Neuroticism', 'Agreeableness', 'Conscientiousness', 'Openness
#1: "average I type"
#2: "role model", N is below, other above
#6: "undercontrolled", all score below average, least agreeable
#7: "Overcontrolled", high N, low E.
#8: "average II type"  all within one standard deviation

```

```{r}
#for each iter, call Posterior Clusters, select cluster size greater than 10%, compile into a list
num_clusters_list <- c()
i=1
for(i in 1:1000){
  post_clust <- PosteriorClusters(my_data,i)
  
  valid_indx <- c()
  for(j in 1:length(post_clust$weights)){
    if(post_clust$weights[j]>0.1){
      valid_indx <- c(valid_indx,j)
    }
  }
  num_clusters_list[i]=length(valid_indx);
  
}

```

```{r}
#Save MCMC
saveRDS(num_clusters_list, file = "cluster_size_MCMC.rds")

```


```{r}
library(dirichletprocess)
post_clust <- PosteriorClusters(my_data)

sum(post_clust$weights>0.01)

valid_indx <- c()
for(i in 1:length(post_clust$weights)){
  if(post_clust$weights[i]>0.1){
    valid_indx <- c(valid_indx,i)
    
  }
}
m <- c()
for(i in valid_indx){
  m <- rbind(m,post_clust$params[[1]][,,i])
}
m[1,]

# Plot cluster means 
par(mfrow=c(2,4))
for(i in 1:5){
  plot(x=1:5,y=m[i,],ylim=c(-3,3),
       xlab = "subtraits",ylab="score", 
       main=paste(" mean for cluster",i),
       sub=paste(round(post_clust$weights[valid_indx[i]]*100,2),"%total population"),
       xaxt="n")
  axis(side = 1, at = 1:5,labels = c("E","N","A","C","O"))
}


```


```{r}
S=1000
length(my_data$alphaChain) 
plot(1:S,my_data$alphaChain,type="l")
my_data$alpha
my_data$alphaChain[1000]
```


```{r}
#load and calculate data 
library(dplyr)

data_raw = read.csv("../data-final.csv", sep='\t', na.strings = "NULL")
data = data.frame(data_raw)
data <- data[ -c(51:107) ]
data <- data[ -c(52:53) ]
data <- na.omit(data)
pos_keyed_vars <-  c('EXT1', 'EXT3', 'EXT5', 'EXT7', 'EXT9',
                    'EST1', 'EST3', 'EST5', 'EST6', 'EST7', 
                    'EST8', 'EST9', 'EST10',
                    'AGR2', 'AGR4', 'AGR6', 'AGR8', 'AGR9', 'AGR10',
                    'CSN1', 'CSN3', 'CSN5', 'CSN7', 'CSN9', 'CSN10', 
                    'OPN1', 'OPN3', 'OPN5', 'OPN7', 'OPN8', 'OPN9', 
                    'OPN10')
neg_keyed_vars <-  c('EXT2', 'EXT4', 'EXT6', 'EXT8', 'EXT10',
                    'EST2', 'EST4',
                    'AGR1', 'AGR3', 'AGR5', 'AGR7', 
                    'CSN2', 'CSN4', 'CSN6', 'CSN8', 
                    'OPN2', 'OPN4', 'OPN6')
for(key in neg_keyed_vars){
  data[key]=6-data[key]
}
data <- data %>% mutate(
  EXT=rowSums(data[1:10]),
  EST=rowSums(data[11:20]),
  AGR=rowSums(data[21:30]),
  CSN=rowSums(data[31:40]),
  OPN=rowSums(data[41:50]))
score_data_final <- data[,52:56]
score_data_final <- scale(score_data_final)
score_data_final<-as.data.frame(score_data_final)



```


```{r}
# Set g and h 
#1000 samples   100 times

g1_samples <- c()
g2_samples <- c()
g3_samples <- c()
g4_samples <- c()
g5_samples <- c()

for(i in 1:1000){
  matrix =cov( sample_n(score_data_final,1000))
  g1_samples[i] <- 1/matrix[1,1]
  g2_samples[i] <- 1/matrix[2,2]
  g3_samples[i] <- 1/matrix[3,3]
  g4_samples[i] <- 1/matrix[4,4]
  g5_samples[i] <- 1/matrix[5,5]
}

gamma_fit1<-fitdist(g1_samples,distr = "gamma", method="mle")
gamma_fit2<-fitdist(g2_samples,distr = "gamma", method="mle")
gamma_fit3<-fitdist(g3_samples,distr = "gamma", method="mle")
gamma_fit4<-fitdist(g4_samples,distr = "gamma", method="mle")
gamma_fit5<-fitdist(g5_samples,distr = "gamma", method="mle")
plot(gamma_fit1)
G <- c(gamma_fit1$estimate[1],gamma_fit2$estimate[1],gamma_fit3$estimate[1],gamma_fit4$estimate[1],gamma_fit5$estimate[1])
H <- c(gamma_fit1$estimate[2],gamma_fit2$estimate[2],gamma_fit3$estimate[2],gamma_fit4$estimate[2],gamma_fit5$estimate[2])

```


```{r}
#final run
#mix AK
library(mixAK)

cluster_final_indx

#LBX final run
Mu=rbind(c(my_data$clusterParameters$mu[,,1]),c(my_data$clusterParameters$mu[,,2]),my_data$clusterParameters$mu[,,6],my_data$clusterParameters$mu[,,7],my_data$clusterParameters$mu[,,8])

Sig=mat_combined1 <- rbind(my_data$clusterParameters$sig[,,1], my_data$clusterParameters$sig[,,2 ],my_data$clusterParameters$sig[,,6 ],my_data$clusterParameters$sig[,,7 ],my_data$clusterParameters$sig[,,8 ]) 

g<-c(g1_samples)

Init<-list(K=5, w=c(my_data$weights[1],my_data$weights[2],my_data$weights[6],my_data$weights[7],my_data$weights[8]),mu=Mu, Sigma=Sig)

NMCMC <- c(burn=1000, keep=5000, thin=5, info=1000)

Prior <- list(priorK = "fixed", Kmax = 5 ,priormuQ="independentC",xi=Mu,D=Sig,g=G,h=H)

fit_personality <- NMixMCMC(y0=sample_n(score_data_final,200000),prior=Prior,init=Init,nMCMC=NMCMC)


```

```{r}
#read result
post_data <- readRDS("Posterior_Final.rds")

# Plot cluster means 
par(mfrow=c(2,3))
for(i in 1:5){
  plot(x=1:5,y=post_data$poster.mean.mu[i,],ylim=c(-3,3),
       xlab = "subtraits",ylab="score", 
       main=paste(" mean for cluster",i),
       sub=paste(round(post_data$poster.mean.w[i]*100,2),"%total population"),
       xaxt="n")
  axis(side = 1, at = 1:5,labels = c("E","N","A","C","O"))
}

```















